ページのスタイル
umezawann/motive pull request #43
Opened 2021-11-10 14:56 UTC by umezawann

close #38

2021-11-11 06:12 UTC, umezawann commented
![pr](https://user-images.githubusercontent.com/79554925/141247148-b827ce88-4ce4-4e7b-b642-46277d767cb8.gif)

2021-11-13 05:12 UTC, keisukee commented on web/pages/signup/index.tsx
> +                          borderRadius: "5px",
TextFieldに対して、`fullWidth`というpropが渡せるので、これでキレイに書けるはず

![image](https://user-images.githubusercontent.com/38725877/141606476-93b30e6c-815d-4bf7-a391-8487f148a6b4.png)

https://mui.com/api/text-field/

2021-11-13 05:12 UTC, keisukee commented on web/pages/login/index.tsx
> +        <div style={{ fontSize: "25px", fontWeight: "bold" }}>ログイン</div>
muiの`styled`を使って、divを`Container`みたいな感じで宣言したい

もしくは、`Stack` （https://mui.com/api/text-field/）や、`Grid`（https://mui.com/components/grid/）を使う

2021-11-13 05:12 UTC, keisukee commented on web/pages/login/index.tsx
> +        <div style={{ fontSize: "25px", fontWeight: "bold" }}>ログイン</div>
style={{}} というのは使いたくない

2021-11-13 05:21 UTC, keisukee requested changes

2021-11-13 05:21 UTC, keisukee commented on web/components/templates/Layouts/AuthLayout.tsx
> +      </Box>
styleは普通にあてられるはず
![image](https://user-images.githubusercontent.com/38725877/141606779-5514984c-6c4a-424d-861d-7081d716ef0d.png)

2021-11-15 13:03 UTC, keisukee approved these changes

2021-11-15 13:03 UTC, merged