labelsにcolorを追加
umezawann/motive pull request #59
Opened 2021-11-17 08:35 UTC by umezawann

close #52
![pr](https://user-images.githubusercontent.com/79554925/142165177-c8ae3748-9784-4b9c-91f2-031c9aac57d4.gif)

2021-11-17 11:25 UTC, umezawann commented on web/components/templates/LabelFormDialog/index.tsx
> +  const [color, setColor] = React.useState<string>('#ccc');
taskには<string>は無かった

2021-11-17 11:25 UTC, umezawann commented on web/components/templates/LabelFormDialog/index.tsx
> +          type="text"
colorもあったが、どちらがいいか

2021-11-17 12:11 UTC, keisukee requested changes

2021-11-17 12:11 UTC, keisukee commented on web/components/templates/LabelFormDialog/index.tsx
> +          type="text"
colorにしよう

2021-11-17 12:12 UTC, keisukee commented
colorをバックエンド側で必須にしたい

2021-11-18 10:17 UTC, umezawann commented
![pr](https://user-images.githubusercontent.com/79554925/142396464-5bbf515f-5ba6-41be-acd4-9d36e20a870d.gif)

2021-11-18 13:39 UTC, keisukee approved these changes

2021-11-18 13:39 UTC, merged