labelの横に・・・追加
umezawann/motive pull request #60
Opened 2021-11-17 09:11 UTC by umezawann

close #54 

![pr](https://user-images.githubusercontent.com/79554925/142170959-afcef2c1-358b-41e4-acd3-6df66c49d50f.gif)

2021-11-17 11:23 UTC, umezawann commented
close #56 
![pr](https://user-images.githubusercontent.com/79554925/142191581-340fd717-6654-48ac-ba73-c2fa58c239ec.gif)

2021-11-17 11:27 UTC, umezawann commented on web/components/templates/Layouts/BaseLayout.tsx
> +    React.useState<HTMLButtonElement | null>(null);
名前こん感じでいいか

2021-11-17 11:29 UTC, umezawann commented on server/src/labels/labels.controller.ts
> +
Postと一緒に書いたら、エラーが出たためコメントアウトした

2021-11-17 11:30 UTC, umezawann commented on web/components/templates/Layouts/BaseLayout.tsx
> -                    </Card>
BaseLayoutのファイルが長すぎる感じがしたので、Labelに移した

2021-11-17 12:15 UTC, keisukee requested changes

2021-11-17 12:15 UTC, keisukee commented on server/src/labels/labels.controller.ts
> +
消してok

2021-11-17 12:15 UTC, keisukee commented on web/components/templates/Label/Label.tsx
> +            </div>
muiで、Stackとか使えば簡単にかけるはず

2021-11-17 12:17 UTC, keisukee commented on web/components/templates/Layouts/BaseLayout.tsx
> +    React.useState<HTMLButtonElement | null>(null);
名前はok

せっかくだし、Labelとlableのmodalを一緒に、別ファイルに切り出してみよう
そうすれば、重複消えるから、両方の名前ももっとシンプルにできるし

2021-11-17 12:19 UTC, keisukee commented
色を変えられるなら、ラベルのアイコンの色をcolorに合わせたい

![image](https://user-images.githubusercontent.com/38725877/142199304-f4dcf68f-020b-4eec-a03e-0a4f7a8f7009.png)

2021-11-18 11:28 UTC, umezawann commented
![pr](https://user-images.githubusercontent.com/79554925/142407122-b7013dbb-6db0-4b5d-bf9a-884efec01e80.gif)

2021-11-18 13:41 UTC, keisukee requested changes

2021-11-18 13:41 UTC, keisukee commented on web/components/templates/Label/Label.tsx
> +import ListItemIcon from "@mui/material/ListItemIcon";
ファイル名は、Label/index.tsxでいいと思う

2021-11-18 13:44 UTC, keisukee requested changes

2021-11-18 13:44 UTC, keisukee commented on web/components/templates/Layouts/BaseLayout.tsx
>          </Drawer>
labels.map(l => <Label label={l} key={l.id}>)
でよい

2021-11-18 13:44 UTC, keisukee commented on web/components/templates/Label/Label.tsx
> +          <ListItemIcon>
mapしているから、モーダルが同時に何個も開いてしまう

ファイルの命名的にもおかしい。複数形なのに、単数形のファイル名だから

2021-11-18 13:54 UTC, keisukee approved these changes

2021-11-18 13:54 UTC, merged